Title:Ismaila Jammeh
# Cybersecurity 
### Education
High school diploma,Technical support fundamentals,Fundation of cybersecurity
### Work Exprience
Business office carmax, Buyer's office carmax, Jfin accountant
show_downloads: true
theme: jekyll-theme-minimal
